/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void textfield3_change1(GTextField source, GEvent event) { //_CODE_:ask_nickname:591933:
  //println("textfield3 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:ask_nickname:591933:

public void imgButton1_click1(GImageButton source, GEvent event) { //_CODE_:imgButton1:716145:
  println("imgButton1 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton1:716145:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  G4P.setDisplayFont("Arial", G4P.PLAIN, 20);
  G4P.setInputFont("Calibri", G4P.PLAIN, 20);
  surface.setTitle("Guess what is that?");
  label4 = new GLabel(this, 269, 176, 152, 40);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("Nickname:");
  label4.setOpaque(false);
  ask_nickname = new GTextField(this, 399, 172, 200, 50, G4P.SCROLLBARS_NONE);
  ask_nickname.setPromptText("Enter your nickname");
  ask_nickname.setOpaque(false);
  ask_nickname.addEventHandler(this, "textfield3_change1");
  imgButton1 = new GImageButton(this, 196, 142, 100, 98, new String[] { "bio.png", "bio.png", "bio.png" } );
  imgButton1.addEventHandler(this, "imgButton1_click1");
}

// Variable declarations 
// autogenerated do not edit
GLabel label4; 
GTextField ask_nickname; 
GImageButton imgButton1; 
